### PR TITLE
Add a new seed type of "style". Useful to do content aware fill.

### PR DESCRIPTION
**Pull request by bmaltais**

### CODE REVIEW

**Comment by alexjc** [comment]
Thanks for the suggestion. I've never really tried seeding from style, but you could specify the filename of the style file instead and use the existing code?

In many cases, the style image is different than the content image. To commit this, it would need a resize using for example `scipy.ndimage.imresize`.

**Comment by bmaltais** [comment]
Might be a silly question but I have not found what is the scipy to actually get the size of a given image. I need to get that to properly set the size of the style. Searching for scipy image size turn nothing ;-( Any idea?

**Comment by bmaltais** [comment]
I think I found it: scipy.misc.imresize(self.style_image[0], shape)

**Comment by alexjc** [comment]
This is now in [4b3ad6d]. Thanks for your help with this!

**Pull request closed without merging**
