### PR TITLE
Create docker images, fix #61

### LINKED ISSUE #61: Docker Images for AWS and Azure
Hi,

I was struggling and wasting too much time installing and setting up all dependencies on spot AWS GPU g2.2xlarge instances between regions and on different Azure machines, so I've decided to create Docker images to ease up the deployment on Ubuntu 14.04. 

If anybody is interested, you can find instructions, Docker files, scripts to install host dependencies, and, of course, images here

For a CPU setup
[github.com/toksaitov/neural-doodle-cpu](http://github.com/toksaitov/neural-doodle-cpu)
For a GPU CUDA setup
[github.com/toksaitov/neural-doodle-gpu](http://github.com/toksaitov/neural-doodle-gpu)
Images on Docker Hub
[hub.docker.com/r/toksaitov/neural-doodle](https://hub.docker.com/r/toksaitov/neural-doodle)

With NVIDIA Docker (with GPU drivers) installed on the host experimenting with the project could be as easy as running

    nvidia-docker run --interactive --tty --volume="$(pwd)/data":/data/ toksaitov/neural-doodle:gpu --style=/data/Style.png --output=/data/Result.png --iterations=160

If you don't want to use GPU acceleration, you just need to install Docker on the host and use it directly

    docker run --interactive --tty --volume="$(pwd)/data":/data/ toksaitov/neural-doodle:cpu --style=/data/Style.png --output=/data/Result.png --iterations=160

Currently the builds are not automatic, but it will be resolved in a week or two.

### PR DESCRIPTION
**Pull request by jiahuif**
Temporarily here:
https://hub.docker.com/r/indeedplusplus/neural-doodle/

Thanks to [toksaitov/neural-doodle-gpu](https://github.com/toksaitov/neural-doodle-gpu)

### CODE REVIEW

**Comment by jiahuif** [comment]
WIP. hold on for a while.

**Comment by jiahuif** [comment]
Finished local build. Looks good for me.
Waiting for Docker Hub

**Comment by jiahuif** [comment]
One question please @alexjc 
why `--ignore-installed` when `pip3 install`?
building scipy takes quite a long time.

**Comment by alexjc** [comment]
It shouldn't rebuild scipy (I must have most recent version), but should reinstall other things locally. If it's a clean docker install it doesn't matter!

**Comment by alexjc** [comment]
Also, can you make just one Docker file for both CPU and GPU? Seems easy enough to pass in the extra argument on the command line rather than have duplicate images.  (The `.theanorc` file is not necessary, the only option not already specified is `fastmath` and if it's better then we should just put it into the `doodle.py` at the top.)

And if you could put as many files as possible into the `#/docker/` subfolder that'd be ideal too! Thanks.

**Comment by jiahuif** [comment]
The problem is, however, the base image. The GPU version requires cuDNN, which takes 745 MB to download and 1.351 GB installed on my disk. The CPU version needs only a simple ubuntu image taking only 66 MB to download and 187.9 MB installed.

**Comment by jiahuif** [comment]
Of course the gpu version can run with cpu too.

**Comment by alexjc** [comment]
Oh, I see. That makes sense to keep them separate then! Sorry, I'll get out of the way now ;-)

**Comment by jiahuif** [comment]
Unfortunately docker hub somehow got jammed. Maybe we need to wait for a while.

**Comment by alexjc** [comment]
I created an account on Docker Hub and associated it with this project. In theory it should build `latest` when a commit happens!
https://hub.docker.com/r/alexjc/neural-doodle/

We'll see once we merge these changes!

**Comment by alexjc** [comment]
After minor setup issues, it works well! I will add a new `latest-gpu` build too.
https://hub.docker.com/r/alexjc/neural-doodle/

**Comment by jiahuif** [comment]
Thanks for merging
FYI, here is my build settings
I am on mobile so I took screenshot to make things easier
http://postimg.org/image/94epn5yxt/full/

**Pull request merged**
